### ISSUE TITLE
Vibration native not working

### ISSUE THREAD

**Issue by Lindstrom1989** [driftyco/ionic-native#106]
Getting error "TypeError: Cannot read property 'apply' of undefined" from browser_adapter.ts

Also getting in browser, can't interface with plugin.

**Comment by ihadeed** [comment]
Can you please provide me with a way to reproduce this issue? as well as the setup you are using (Platform, Framework .. etc)

**Comment by Lindstrom1989** [comment]
Hi yes my system info is

**Comment by Lindstrom1989** [comment]
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.4
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.3 Build version 7D175

**Comment by Lindstrom1989** [comment]
Hi yes my system info is:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.4
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.3 Build version 7D175

Using ios @mhartington reproduced with the same issue, simply downloading the plugin, then
`import {Vibration} from 'ionic-native';`

**Comment by Lindstrom1989** [comment]
Also noticed this error in my terminal on building, could be related?

**Comment by ihadeed** [comment]
@Lindstrom1989 What version of Angular 2 are you using?

**Comment by Lindstrom1989** [comment]
2.0.0-beta.6

**Comment by ihadeed** [comment]
Upgrade to beta.7 or later and that should solve the problem.

**Comment by Lindstrom1989** [comment]
Nope still getting "ERROR: ORIGINAL EXCEPTION: TypeError: undefined is not an object (evaluating 'util_1.get(window, pluginObj.pluginRef)[methodName].apply')" on my end.

**Comment by tlancina** [comment]
It looks like the plugin defines only the vibrate function on `window.navigator`, @ihadeed are there any other plugins like this? I can't think of an easy way to fix this off the top of my head other than setting the pluginRef to just `navigator`, which seems weird.

**Comment by ihadeed** [comment]
@tlancina I see the problem now. The plugin ref is incorrect. I think this is the only plugin that works this way.
