### ISSUE TITLE
Deeplinks: change detection not working

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic-native#1371]
When opening a page through `ionic-plugin-deeplinks` using `routeWithNavController`, change detection is not working on that page and any pages navigated to from that page.

I'm using the latest 3.4.4.

Is there a way to manually make this work while the bug is around? Should I run it inside zone?

**Comment by Manduro** [comment]
```ts
this.deeplinks.route(routes).subscribe(match => {
  console.warn('Successfully routed', match);
  console.warn(NgZone.isInAngularZone()); // false
  this.ngZone.run(() => {
    console.warn(NgZone.isInAngularZone()); // true
    this.navCtrl.push(match.$route, match.$args);
  });
}, nomatch => {
  console.warn('Unmatched Route', nomatch);
});
```

This makes it work again, so definitely a bug here somewhere!

**Comment by ihadeed** [comment]
This should be fixed if you're using latest Ionic Native and Angular 4.x

**Comment by ryandegruyter** [comment]
Still having this issue with

"@angular/core": "4.1.2",
"@ionic-native/core": "3.12.1",

**Comment by Manduro** [comment]
@ryandegruyter I haven't tested yet if it has been fixed, but updating `zone.js` to `0.8.12` could be relevant. You could give that a try!

https://github.com/angular/zone.js/blob/master/CHANGELOG.md#0812-2017-06-07

**Comment by ryandegruyter** [comment]
Thanks for the quick response @Manduro!

I just tested upgrading zone.js to 0.8.12 but unfortunately it's still not working. 

I'm using your first solution by injecting ngZone in the meantime.
