### ISSUE TITLE
Latest update causes 'plugin not found' error

### ISSUE THREAD

**Issue by joshuamorony** [driftyco/ionic-native#185]
Any project containing the latest version of Ionic Native will receive the following error:

`googlemaps.js:15 Uncaught ReferenceError: plugin is not defined`

Steps to reproduce:
1. Generate a new application
2. Run `ionic serve`

**Comment by jgw96** [comment]
I am also getting the same error when trying to start a new project using any of our starters.

**Comment by juanqui** [comment]
Same here. I have pinned the version to 1.2.2 in my Ionic 2 app for the meantime.

**Comment by macchie** [comment]
edit your package.json file and check your ionic-native version is set to “1.2.3” (or latest, check the github repo), (mine was 1.1.0) then run "npm install" in your app folder to get the updated dependency

**Comment by mrweiland** [comment]
Same problem here. As @juanqui said you need to pin down to version 1.2.2 and then run npm install. :(

**Comment by jgw96** [comment]
Hey community! This should be fixed now. There is an issue in 1.2.3 that needs to be resolved, but to get it fixed pronto i have pinned ionic native to 1.2.2 and did a roll back on the 1.2.3 release. Very sorry for the trouble!

**Comment by ihadeed** [comment]
Sorry for the trouble everyone.

I fixed the issue and published a new update (v1.2.4).

**Comment by KaushikRay** [comment]
I am still getting this with 1.3.2 . Added https://github.com/driftyco/ionic-native/issues/303

**Comment by Kayrohinc** [comment]
In 1.3.9 bug comes again , plugin is not defined on serve and on android build.
D/StatusBar.MSimNetworkController( 1192): refreshSignalCluster, mMSimPhoneSignalIconId[0]=com.android.systemui:drawable/old_stat_sys_signal_4_fully mMSimDataSignalIconId[0]=com.android.systemui:drawable/old_stat_sys_signal_4_fully mMSimDataTypeIconId[0]=com.android.systemui:drawable/stat_sys_data_fully_connected_4g mMSimMobileActivityIconId[0]=(null) mNoMSimIconId[0]=(null)
I/chromium(15111): [INFO:CONSOLE(33659)] "EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
I/chromium(15111): ORIGINAL EXCEPTION: ReferenceError: plugin is not defined
I/chromium(15111): ORIGINAL STACKTRACE:
I/chromium(15111): ReferenceError: plugin is not defined
I/chromium(15111): at new GoogleMap (file:///android_asset/www/build/js/app.bundle.js:73664:32)

**Comment by ng-mohit** [comment]
still getting the same with 1.3.10 while working with google maps in ionic2
