### ISSUE TITLE
Module has no exported member 'Location Accuracy'

### ISSUE THREAD

**Issue by junaidahmed93** [driftyco/ionic-native#622]
Hello everyone,
I am getting error while importing LocationAccuracy from ionic native
`Module has no exported member 'Location Accuracy'`
I have already installed the plugin.
Is there any solution?

**Comment by junaidahmed93** [comment]
Following this code snippet from IONIC 2 native

import { LocationAccuracy } from 'ionic-native';

LocationAccuracy.canRequest().then((canRequest: boolean) => {

if(canRequest) {
// the accuracy option will be ignored by iOS
LocationAccuracy.request(LocaitonAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY).then(
() => console.log('Request successful'),
error => console.log('Error requesting location permissions', error)
);
}

});

**Comment by ihadeed** [comment]
Fixed now, please update to latest version.

**Comment by junaidahmed93** [comment]
This issue is not fixed , still facing same error after updating 
`Module has no exported member 'Location Accuracy'`

``` 
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v4.5.0
```
