### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by mebibou** [driftyco/ionic-native#882]
When testing locally on Chrome using `ionic server`, the following code produces an error:
```js
ScreenOrientation.lockOrientation('portrait');
```
The error is:
```
Uncaught (in promise): TypeError: Cannot read property 'apply' of undefined
```

The code needs to be surrounded by a try/catch in order to make the app work

```sh
$ ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by ihadeed** [comment]
Can you run `ionic info` in your project folder.

**Comment by mebibou** [comment]
@ihadeed updated the description

**Comment by bnoeson** [comment]
I also have this error, not only with ionic serve, but also when running on Android.
Here is what error says : 
```
`TypeError: Cannot read property 'apply' of undefined
    at callCordovaPlugin (file:///android_asset/www/build/js/app.bundle.js:93457:63)
    at Function.<anonymous> (file:///android_asset/www/build/js/app.bundle.js:93597:20)
    at Function.value [as lockOrientation] (file:///android_asset/www/build/js/app.bundle.js:93660:61)`
```
ionic info
```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v4.4.7
```
(OS is actually windows 10)

**Comment by ihadeed** [comment]
@mebibou this would be the same issue here: https://github.com/driftyco/ionic-native/issues/814#issuecomment-263903300

ScreenOrientation plugin uses `window.screen` which is defined in every browser, but the plugin specific properties are only available in Cordova environment.

**Comment by ihadeed** [comment]
@bnoeson Crosswalk fires the `deviceready` even before it's ready, wrap your code with `setTimeout` and give it ~100ms and it should work (increase the timeout if needed).

**Comment by ivanovvitaly** [comment]
I have the same issue. It fails even if you just import the plugin using import { ScreenOrientation } from 'ionic-native'; 
When the app gets the page with import it fails with error.
Please advice

**Comment by ihadeed** [comment]
Just pushed a commit that should fix this. I wrapped the `.apply` call with try/catch so it can handle cases like this. The fix will be available in the next release.

**Comment by jonathan-chin** [comment]
subscribing to this. does the try/catch block mean that we won't be able to rely on this to lock the orientation? if so, what are the roadblocks to finding a long term solution?

**Comment by ihadeed** [comment]
@jonathan-chin I got rid of the `try/catch` block. I fixed this issue in another way in a different commit.

**Comment by supryin** [comment]
@ihadeed I am still facing that problem. Using ionic-native 2.5.1 .
 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.5.0
Xcode version: Not installed

Here is my code:
setTimeout(ScreenOrientation.lockOrientation("landscape"),500);

Thank you!

**Comment by mordka** [comment]
@supryin, you need to build browser platform and run ionic-serve pointing it's build output [see this issue](https://github.com/danwilson/google-analytics-plugin/issues/361#issuecomment-272020296)
